name: Publish Docker image to ghcr.io
on:
  # publish on releases (tagged as "x.y.z" - "v" prefix is removed)
  release:
    types: [published]

  # publish on pushes to the main branch
  push:
    branches:
      - main

jobs:
  docker_publish:
    runs-on: "ubuntu-20.04"

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v3.5.2

      # https://github.com/marketplace/actions/push-to-ghcr
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
